apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  serviceName: registry-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
        app.kubernetes.io/name: registry
        app.kubernetes.io/instance: registry
        app.kubernetes.io/version: v2
        app.kubernetes.io/component: container-registry
        app.kubernetes.io/part-of: registry
        app.kubernetes.io/managed-by: launchcpx
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - name: registry
              containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
