apiVersion: 'networking.istio.io/v1alpha3'
kind: 'VirtualService'
metadata:
  name: 'registry'
spec:
  gateways:
    - 'istio-system/istio-gateway'
  hosts:
    - 'docker.pkg.dev.home'
  http:
    - route:
        - destination:
            host: 'registry'
            port:
              number: 5000
