apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'nats-internal'
spec:
  selector:
    component: 'nats-server'
  ports:
    - name: 'client'
      port: 4222
    - name: 'cluster'
      port: 6222
  clusterIP: 'None'
