apiVersion: 'networking.istio.io/v1alpha3'
kind: 'VirtualService'
metadata:
  name: 'whoami'
spec:
  gateways:
    - 'istio-gateway'
  hosts:
    - 'whoami.dev.home'
  http:
    - route:
        - destination:
            host: 'whoami'
            port:
              number: 8080
