apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
secretGenerator:
  - name: kiali
    literals:
      - username=admin
      - passphrase=admin
generatorOptions:
  disableNameSuffixHash: true
resources:
  - operator.yaml
