apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'
namespace: 'istio-system'
commonLabels:
  app.kubernetes.io/name: 'istio-controlplane'
  app.kubernetes.io/instance: 'istio-controlplane'
  app.kubernetes.io/version: '1.5'
  app.kubernetes.io/component: 'istio-controlplane'
  app.kubernetes.io/part-of: 'istio'
  app.kubernetes.io/managed-by: 'launchcpx'
resources:
  - 'operator.yaml'
