apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
spec:
  selector:
    matchLabels:
      app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        app: metrics-server
        app.kubernetes.io/name: metrics-server
        app.kubernetes.io/instance: metrics-server
        app.kubernetes.io/version: v0.3
        app.kubernetes.io/component: kube-metrics
        app.kubernetes.io/part-of: metrics
        app.kubernetes.io/managed-by: launchcpx
    spec:
      serviceAccountName: metrics-server
      containers:
        - name: metrics-server
          image: k8s.gcr.io/metrics-server/metrics-server:v0.3.7
          args:
            - --cert-dir=/tmp
            - --secure-port=4443
          ports:
            - name: main-port
              containerPort: 4443
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
      volumes:
        - name: tmp-dir
          emptyDir: {}

---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100

---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  labels:
    kubernetes.io/name: 'Metrics-server'
    kubernetes.io/cluster-service: 'true'
spec:
  selector:
    k8s-app: metrics-server
  ports:
    - port: 443
      protocol: TCP
      targetPort: main-port
