apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: config
    files:
      - redis.conf
  - name: init-scripts
    files:
      - init.sh
      - _init_lib.sh
resources:
  - statefulset.yaml
  - service.yaml
  - headlessservice.yaml
  - serviceaccount.yaml
