apiVersion: 'apps/v1'
kind: 'StatefulSet'
metadata:
  name: 'redis'
spec:
  selector:
    matchLabels:
      component: 'redis-server'
  serviceName: 'redis-internal'
  replicas: 1
  template:
    metadata:
      labels:
        component: 'redis-server'
    spec:
      serviceAccountName: 'redis'
      initContainers:
        - name: 'genpass'
          image: 'xorkevin/alpine-utils:3'
          command: ['sh']
          args: ['/home/redis/init.sh']
          env:
            - name: 'PASS_LEN'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'passlen'
                  optional: true
            - name: 'VAULT_ADDR'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'vaultaddr'
            - name: 'VAULT_ROLE'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'vaultrole'
            - name: 'KV_PATH'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'kvpath'
          volumeMounts:
            - name: 'config-pass'
              mountPath: '/etc/redispass'
            - name: 'init-scripts'
              mountPath: '/home/redis'
      containers:
        - name: 'redis'
          image: 'redis:5-alpine'
          command: ['redis-server']
          args: ['/etc/redis/redis.conf']
          ports:
            - containerPort: 6379
              name: 'redis'
          volumeMounts:
            - name: 'config'
              mountPath: '/etc/redis'
            - name: 'config-pass'
              mountPath: '/etc/redispass'
      volumes:
        - name: 'config'
          configMap:
            name: 'redis-config'
        - name: 'init-scripts'
          configMap:
            name: 'init-scripts'
        - name: 'config-pass'
          emptyDir: {}
  volumeClaimTemplates: []
