apiVersion: 'apps/v1'
kind: 'StatefulSet'
metadata:
  name: 'redis'
spec:
  selector:
    matchLabels:
      component: 'redis-server'
  serviceName: 'redis-internal'
  replicas: 1
  template:
    metadata:
      labels:
        component: 'redis-server'
    spec:
      serviceAccountName: 'redis'
      initContainers:
        - name: 'genpass'
          image: 'busybox:1'
          command: ['sh', '-c']
          args:
            - >-
              echo 'begin genpass'
              && k=$(head -c ${PASS_LEN:-128} < /dev/urandom | base64 | tr -d '\n=' | tr '+/' '-_')
              && echo 'generate password'
              && echo -n $k > /home/pass/pass
              && echo 'write password to shared volume with initvault'
              && echo "requirepass $k" > /etc/redispass/pass.conf
              && echo 'write password to shared volume with redis'
          env:
            - name: 'PASS_LEN'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'passlen'
                  optional: true
          volumeMounts:
            - name: 'config-pass'
              mountPath: '/etc/redispass'
            - name: 'tmp-pass'
              mountPath: '/home/pass'
        - name: 'initvault'
          image: 'vault:1.4.0'
          command: ['sh', '-c']
          args:
            - >-
              echo 'begin initvault'
              && mkdir -p /home/vault
              && echo 'create vault home'
              && vault agent -config=/etc/vault/agent-config.hcl
              && echo 'authenticate with vault'
              && export VAULT_TOKEN=$(cat /home/vault/.token)
              && echo 'read vault token'
              && vault kv put $KV_PATH password=$(cat /home/pass/pass)
              && echo 'write password to vault kv'
          env:
            - name: 'VAULT_ADDR'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'vaultaddr'
            - name: 'KV_PATH'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'kvpath'
          volumeMounts:
            - name: 'agent-config'
              mountPath: '/etc/vault'
            - name: 'tmp-pass'
              mountPath: '/home/pass'
      containers:
        - name: 'redis'
          image: 'redis:5-alpine'
          ports:
            - containerPort: 6379
              name: 'redis'
          volumeMounts:
            - name: 'config'
              mountPath: '/etc/redis'
            - name: 'config-pass'
              mountPath: '/etc/redispass'
      volumes:
        - name: 'config'
          configMap:
            name: 'redis-config'
        - name: 'agent-config'
          configMap:
            name: 'redis-agent-config'
        - name: 'config-pass'
          emptyDir: {}
        - name: 'tmp-pass'
          emptyDir: {}
  volumeClaimTemplates: []
