apiVersion: 'apps/v1'
kind: 'StatefulSet'
metadata:
  name: 'redis'
spec:
  selector:
    matchLabels:
      component: 'redis-server'
  serviceName: 'redis-internal'
  replicas: 1
  template:
    metadata:
      labels:
        component: 'redis-server'
    spec:
      serviceAccountName: 'redis'
      initContainers:
        - name: 'genpass'
          image: 'alpine:3'
          command: ['sh', '-c']
          args:
            - >-
              echo 'begin genpass'
              && apk --no-cache add curl jq
              && pass=$(head -c ${PASS_LEN:-64} < /dev/urandom | base64 | tr -d '\n=' | tr '+/' '-_')
              && echo 'generate password'
              && satoken=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              && echo 'read service account token'
              && token=$(curl -s -X POST -d "{\"jwt\": \"${satoken}\", \"role\": \"${KV_ROLE}\"}" ${VAULT_ADDR}/v1/auth/kubernetes/login | jq -r '.auth.client_token')
              && echo 'authenticate with vault'
              && curl -s -H "X-Vault-Token: ${token}" -X POST -d "{\"data\": {\"password\": \"${pass}\"}}" ${VAULT_ADDR}/v1/${KV_PATH} > /dev/null
              && echo 'write password to vault kv'
              && echo "requirepass ${pass}" > /etc/redispass/pass.conf
              && echo 'write password to redis conf'
          env:
            - name: 'PASS_LEN'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'passlen'
                  optional: true
            - name: 'VAULT_ADDR'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'vaultaddr'
            - name: 'KV_ROLE'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'vaultrole'
            - name: 'KV_PATH'
              valueFrom:
                configMapKeyRef:
                  name: 'redis-opts'
                  key: 'vaultpath'
          volumeMounts:
            - name: 'config-pass'
              mountPath: '/etc/redispass'
      containers:
        - name: 'redis'
          image: 'redis:5-alpine'
          command: ['redis-server']
          args: ['/etc/redis/redis.conf']
          ports:
            - containerPort: 6379
              name: 'redis'
          volumeMounts:
            - name: 'config'
              mountPath: '/etc/redis'
            - name: 'config-pass'
              mountPath: '/etc/redispass'
      volumes:
        - name: 'config'
          configMap:
            name: 'redis-config'
        - name: 'config-pass'
          emptyDir: {}
  volumeClaimTemplates: []
