apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'
commonLabels:
  app.kubernetes.io/name: 'minio'
  app.kubernetes.io/instance: 'minio'
  app.kubernetes.io/version: 'latest'
  app.kubernetes.io/component: 'objstore'
  app.kubernetes.io/part-of: 'minio'
  app.kubernetes.io/managed-by: 'launchcpx'
configMapGenerator:
  - name: 'init-scripts'
    files:
      - 'init.sh'
      - '_init_lib.sh'
  - name: 'start-scripts'
    files:
      - 'start.sh'
resources:
  - 'statefulset.yaml'
  - 'service.yaml'
  - 'headlessservice.yaml'
  - 'serviceaccount.yaml'
