apiVersion: 'apps/v1'
kind: 'StatefulSet'
metadata:
  name: 'minio'
spec:
  selector:
    matchLabels:
      component: 'minio-server'
      version: 'latest'
  serviceName: 'minio-internal'
  replicas: 1
  template:
    metadata:
      labels:
        component: 'minio-server'
        version: 'latest'
    spec:
      containers:
        - name: 'minio'
          image: 'latest'
          command: ['server']
          args: ['/var/lib/minio/data']
          ports:
            - name: 'minio'
              containerPort: 9000
          volumeMounts:
            - name: 'data'
              mountPath: '/var/lib/minio'
  volumeClaimTemplates:
    - metadata:
        name: 'data'
      spec:
        accessModes:
          - 'ReadWriteOnce'
        resources:
          requests:
            storage: '32Gi'
