apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-system
configMapGenerator:
  - name: grafana-config
    files:
      - grafana.ini
  - name: datasources
    files:
      - datasources.yaml
resources:
  - service.yaml
  - ingressroute.yaml
