apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'
namespace: 'prometheus-system'
commonLabels:
  app.kubernetes.io/name: 'grafana'
  app.kubernetes.io/instance: 'grafana'
  app.kubernetes.io/version: '7.1'
  app.kubernetes.io/component: 'metrics'
  app.kubernetes.io/part-of: 'prometheus'
  app.kubernetes.io/managed-by: 'launchcpx'
configMapGenerator:
  - name: 'grafana-config'
    files:
      - 'grafana.ini'
  - name: 'datasources'
    files:
      - 'datasources.yaml'
resources:
  - 'service.yaml'
