apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-system
configMapGenerator:
  - name: config
    files:
      - prometheus.yaml
resources:
  - namespace.yaml
  - rbac.yaml
  - service.yaml
