apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'
namespace: 'prometheus-system'
commonLabels:
  app.kubernetes.io/name: 'prometheus'
  app.kubernetes.io/instance: 'prometheus'
  app.kubernetes.io/version: '2.20'
  app.kubernetes.io/component: 'metrics'
  app.kubernetes.io/part-of: 'prometheus'
  app.kubernetes.io/managed-by: 'launchcpx'
configMapGenerator:
  - name: 'config'
    files:
      - 'prometheus.yml'
resources:
  - 'namespace.yaml'
  - 'rbac.yaml'
  - 'service.yaml'
