apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-server

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-internal
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
  clusterIP: 'None'

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
      version: v2.20
  serviceName: prometheus-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        version: v2.20
    spec:
      serviceAccountName: prometheus-server
      containers:
        - name: prometheus
          image: prom/prometheus:v2.20.1
          command: ['/bin/prometheus']
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/var/lib/prometheus/data'
            - '--storage.tsdb.retention.time=15d'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
          ports:
            - name: prometheus
              containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /var/lib/prometheus
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
