apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'
namespace: 'default'
commonLabels:
  app.kubernetes.io/name: 'postgres'
  app.kubernetes.io/instance: 'vault'
  app.kubernetes.io/version: '12'
  app.kubernetes.io/component: 'database'
  app.kubernetes.io/part-of: 'postgres'
  app.kubernetes.io/managed-by: 'launchcpx'
resources:
  - 'statefulset.yaml'
  - 'service.yaml'
