server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

  extraVolumes:
    - type: 'secret'
      name: 'vault-storage-config'

  extraArgs: '-config=/vault/userconfig/vault-storage-config/config.hcl'

  service:
    enabled: true

  dataStorage:
    enabled: false

ui:
  enabled: true
  serviceType: 'LoadBalancer'
