server:
  image:
    repository: vault
    tag: '1.4.2'
    pullPolicy: IfNotPresent

  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          telemetry {
            unauthenticated_metrics_access = true
          }
        }
        storage "raft" {
          path = "/vault/data"
        }
        telemetry {
          prometheus_retention_time = "10m"
          disable_hostname = true
        }
        service_registration "kubernetes" {}

  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8200'
    prometheus.io/path: '/v1/sys/metrics'

  service:
    enabled: true

  dataStorage:
    enabled: true

injector:
  enabled: false

ui:
  enabled: true
