server:
  image:
    repository: 'vault'
    tag: '1.3.4'
    pullPolicy: 'IfNotPresent'

  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true

  service:
    enabled: true

  dataStorage:
    enabled: true

injector:
  agentImage:
    repository: 'vault'
    tag: '1.3.4'
    pullPolicy: 'IfNotPresent'

ui:
  enabled: true
  serviceType: 'LoadBalancer'
